Repository expressjs/discussions, pull requests merged in 2025-05, with the labels that each got.

#366 ✨ ADR: action pinning
  docs/adr/action-pinning.md
Labels: top priority, tc agenda

#298 ADR policy for adoption of OSSF Scorecard
  docs/adr/adr-xxx-adoption-of-ossf-scorecard-for-express.md
Labels: ADR

#382 ✨ lint markdown and add CI
  .github/workflows/lintyMcLintface.yml
  .gitignore
  .markdownlint-cli2.jsonc
  .markdownlint.yml
  .npmrc
  docs/CHARTER.md
  docs/GOVERNANCE.md
  docs/LTS-strategy.md
  docs/adr/290-using-caret-with-dependencies.md
  docs/adr/306-performance-wg.md
  docs/adr/352-lts-strategy.md
  docs/adr/adr-xxx-adoption-of-ossf-scorecard-for-express.md
  docs/contributing/captains_and_committers.md
  docs/contributing/readme-guide.md
  docs/contributing/release-process.md
  docs/contributing/triager-guide.md
  package.json
Labels: fast track
